### PR TITLE
HTML Form project

### PR DESCRIPTION
**Pull request by MiguelDP4**
HTML project imitating the mint.com signup page.

On this branch we worked on the entire page, including:

The signup button
The logo to external sites included in the signup
The form to create an account (front end only)
The footer of the page
The privacy settings fixed position button
By using CSS and HTML only.

Fixed formatting issues, checked with linters.

### CODE REVIEW

**Review by Forison — CHANGES_REQUESTED** [review]
## Status: require changes🛑
# Hi team👋,
Your project output is awesome but does not meet the requirement. Here are a few things we have to do to get this project approved🙂
* [x] You did not configure **linters** as required. I suggest you read this [article](https://github.com/microverseinc/linters-config#linters-config). 
NOTE: stickler and linters setting and configs are mandatory from this project onwards
* [ ] It shows the Mint logo and text (logo on the left, text on the right) ([link to page](https://accounts.intuit.com/signup.html))
* [ ] It shows the Quickbooks logo and text (logo on the left, text on the right) ([link to page](https://accounts.intuit.com/signup.html))
* [ ] It shows the Turbotax logo and text (logo on the left, text on the right) ([link to page](https://accounts.intuit.com/signup.html))
### That is it, Kindly make these changes and submit the project for review
#### Happy coding
[Addo Forison](https://www.linkedin.com/feed/)

**Comment by MiguelDP4** [comment]
> ## Status: require changes
> # Hi team,
> Your project output is awesome but does not meet the requirement. Here are a few things we have to do to get this project approved
> 
> * [ ]  You did not configure **linters** as required. I suggest you read this [article](https://github.com/microverseinc/linters-config#linters-config).
>   NOTE: stickler and linters setting and configs are mandatory from this project onwards
> * [ ]  It shows the Mint logo and text (logo on the left, text on the right) ([link to page](https://accounts.intuit.com/signup.html))
> * [ ]  It shows the Quickbooks logo and text (logo on the left, text on the right) ([link to page](https://accounts.intuit.com/signup.html))
> * [ ]  It shows the Turbotax logo and text (logo on the left, text on the right) ([link to page](https://accounts.intuit.com/signup.html))
> 
> ### That is it, Kindly make these changes and submit the project for review
> #### Happy coding
> [Addo Forison](https://www.linkedin.com/feed/)

Hello!
I was checking the sign in site, and apparently the icons don't always show up in the same order. When we made our project, mint was the first one, quickbooks was the second one and turbotax was the third one. We can change the order of the icons, and it will take less than five minutes, but I fear that if we do it, you will check again and the original site icons will change positions again.

* [x] You did not configure **linters** as required. I suggest you read this [article](https://github.com/microverseinc/linters-config#linters-config). 
NOTE: stickler and linters setting and configs are mandatory from this project onwards
* [x] It shows the Mint logo and text (logo on the left, text on the right) ([link to page](https://accounts.intuit.com/signup.html))
* [x] It shows the Quickbooks logo and text (logo on the left, text on the right) ([link to page](https://accounts.intuit.com/signup.html))
* [x] It shows the Turbotax logo and text (logo on the left, text on the right) ([link to page](https://accounts.intuit.com/signup.html))

**Review by pelzolga123 — CHANGES_REQUESTED** [review]
Project requires changes.

**Comment by pelzolga123** [comment]
## Hi Team!  
### Your project looks :+1: amazing!

Here a few more things you need to change before this project can be approved:

* [ ] Form should have an `<input>` of type `email` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/html_forms/form_and_input_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59524927/))
* [ ]  Form should have an `<input>` of type `tel` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/html_forms/form_and_input_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59524927/))
* [ ] Form should have an `<input>` of type `password` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/html_forms/form_and_input_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59524927/))
* [ ] `Learn more` is missing `href="#"`

[OPTIONAL]
* It's a good practice to use the [`<main>` tag](https://www.w3schools.com/tags/tag_main.asp) for the dominant content of the `<body>` of a document.
* It's a good practice to use the [`<footer>`](https://www.w3schools.com/TagS/tag_footer.asp) tag for the footer.

### Please kindly fix the above issues and send another code review request.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

**Comment by Dandush03** [comment]
> ## Hi Team! 
> ### Your project looks  amazing!
> Here a few more things you need to change before this project can be approved:
> 
> * [ ]  Form should have an `<input>` of type `email` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/html_forms/form_and_input_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59524927/))
> * [ ]   Form should have an `<input>` of type `tel` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/html_forms/form_and_input_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59524927/))
> * [ ]  Form should have an `<input>` of type `password` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/html_forms/form_and_input_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59524927/))
> * [ ]  `Learn more` is missing `href="#"`
> 
> [OPTIONAL]
> 
> * It's a good practice to use the [`<main>` tag](https://www.w3schools.com/tags/tag_main.asp) for the dominant content of the `<body>` of a document.
> * It's a good practice to use the [`<footer>`](https://www.w3schools.com/TagS/tag_footer.asp) tag for the footer.
> 
> ### Please kindly fix the above issues and send another code review request.
> If you have any questions or need help, you can message me on slack (@ Olga Pelts). _Happy coding_

Hello again, we finished fixing the fallowing issues:

* [x] Form should have an `<input>` of type `email` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/html_forms/form_and_input_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59524927/))
* [x]  Form should have an `<input>` of type `tel` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/html_forms/form_and_input_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59524927/))
* [x] Form should have an `<input>` of type `password` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/html_forms/form_and_input_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59524927/))
* [x] `Learn more` is missing `href="#"`

**Review by pelzolga123 — APPROVED** [review]
Approved.

**Comment by pelzolga123** [comment]
## Great  work, Congratulation :+1: Project Approved.
You did all changes required previously. Go ahead and merge to master.
_Goodluck in your next project_ *Happy coding*

**Pull request merged**
